version: '3.9'

services:
  postgres:
    container_name: postgress
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - storage_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME_STATS:?err}
      - POSTGRES_USER=${DB_USER_STATS:?err}
      - POSTGRES_PASSWORD=${DB_PASSWORD_STATS:?err}
      
  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    
volumes:
  postgres_data:
  redis_data:
