services:
  postgres:
    container_name: rvrb2_postgres
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - stack.env
    networks:
      - external_network
    ports:
      - 5432:5432
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.postgres.entrypoints=postgres
      - traefik.tcp.routers.postgres.rule=HostSNI(`*`)
      - traefik.tcp.routers.postgres.tls=false
      - traefik.tcp.services.postgres.loadbalancer.server.port=5432
      - traefik.tcp.routers.postgres.service=postgres
      
  redis:
    container_name: rvrb2_redis
    image: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - external_network
    ports:
      - 6379:6379
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.redis.entrypoints=redis
      - traefik.tcp.routers.redis.rule=HostSNI(`*`)
      - traefik.tcp.routers.redis.tls=false
      - traefik.tcp.services.redis.loadbalancer.server.port=6379
      - traefik.tcp.routers.redis.service=redis

  mongo:
    container_name: rvrb2_mongo
    image: mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data
    env_file:
      - stack.env
    ports:
      - 27017:27017
    networks:
      - external_network
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.mongo.entrypoints=mongo
      - traefik.tcp.routers.mongo.rule=HostSNI(`*`)
      - traefik.tcp.routers.mongo.tls=false
      - traefik.tcp.services.mongo.loadbalancer.server.port=27017
      - traefik.tcp.routers.mongo.service=mongo

  whoami:
    container_name: rvrb2_whoami
    image: traefik/whoami
    networks:
      - external_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.${ROOT_DOMAIN}`)
      - traefik.http.routers.whoami.middlewares=jwt-plugin
      - traefik.http.routers.whoami.entrypoints=websecure

volumes:
  postgres_data:
  redis_data:
  mongo_data:

networks:
  external_network:
    external: true
